language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "pic_map-test";' -U postgres
script:
  - npm test
  - npm run build-client
before_deploy:
  - rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: my-city-pics
  api_key:
    secure: pPnq3K8APJ5ddrZQTEHYoN+goCdvaP7urH0BrcbtCs6FgNsGmEd6wkCouPT+xyxQAuDjXgGG2YCZem6NVj2Z37xScytsowXX4/nkLLI5PXGL7kNFUupmk3apDED8Z6Cm4JsY5ZVsvi3BTNNYzcGHYxT3DaDDnQQyyv0uRJ2NWPt0URptfaOuNHSP01mb/pM3ngGo0TIaqQC7bR12jJWdqJkmn+VU+VyQs/Ph/aD1kN2XqoueCk3HqriyIvaM29RCqALP8SUglBTb7eW/sh0x95+8vCKDIzwmKs8JMVRkbqupPxqsqClDAJbAMWUbwyBGJeHWMD02Wc1cZpcpC/goka10ctONI89eWc1csoeFRm7Jx/JTNR9m9T1qLNhHHp83pGNtpHxlWLS5lNbZBajVSTwrPK0eSn2c6RWfd847cwqInMEWqLKaWtNQ+/MyFJQyOCdN6Q2VVu0yttsB8qNud2rxsq5gQohLOj7gZ7N96Zsmr12b/EVAh5SdHcqeEB39Xz+uvvnqclGlI/NR6fyPIeLTxXJPwihU+J+b57iAx0YN4cIGSm7i0HCzK4gSkGRlwhOMWrw9v4QLj4Aj3ryZToCVRvjegT9sP9m6VN8qxFd2+uclNhBMYV6L0/f0fXiQUVqD5KY1JSqYyoYNalpzdf18hFPyfwE74N4h785RRBs=
